### PR TITLE
Implemented Offline Search

### PR DESCRIPTION
**Pull request by VKumar786**
# Pull Request
Implemented local search using `@easyops-cn/docusaurus-search-local`.

### Fixes: #24 

Screenshot from 2024-01-08 17-36-02

### CODE REVIEW

**Review by abhi1693 — CHANGES_REQUESTED** [review]
This does not work in vercel. Are there additional steps to build the search cache?

**Review by abhi1693 — CHANGES_REQUESTED** [review]
Algolia should also be removed as part of this PR as we want only 1 type of search to be included

**Comment by abhi1693** [comment]
Saw more issues trying to run this locally

```
$ docusaurus start
[INFO] Starting the development server...
Warn: `blogDir` doesn't exist: "/home/asaharan/PycharmProjects/cloudmydc-docs/blog".
[WARNING] Duplicate routes found!
- Attempting to create page at /search, but a page already exists at this route.
This could lead to non-deterministic routing behavior.
```

**Comment by VKumar786** [comment]
Sir There were broken links fail in this code. I think it is because of merge of dev branch.

**Comment by abhi1693** [comment]
Add a new GitHub issue to fix these links and raise a separate pr to fix the problem

**Pull request closed without merging**
